### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dirtyboi** [fake-name/DanbooruScraper#2]
There are 2 more image sites similar to Gelbooru: xbooru.com and tbib.org

And for the scraping: I think it would be much easier to write a [Scrapy](https://scrapy.org/) spider, or not?

Also maybe of interest: If you want to do this professionally, there is a project to download from such image sites: [Hydrus Network](https://hydrusnetwork.github.io/hydrus/). Also in python.

BR,

Dirty Boi

**Comment by fake-name** [comment]
Scrapy might be fancy, but considering I'm really, **really** familiar with just using beautifulsoup and a database manually, it'd certainly not be faster or easier *for me*.

Hydrus network is a desktop client application with a UI and crap, which is very different from this. 

Also, please define "professionally". This scraper fetches everything, I don't know how more serious you can get. 

My [major project scraper](https://github.com/fake-name/ReadableWebProxy) uses my [autotriever](https://github.com/fake-name/AutoTriever) distributed RPC scraping system, and I could point this at that too, but it's not really  warranted.

**Comment by fake-name** [comment]
Wait, are you going about bothering people about using scrapy for some reason?

If you're not going to contribute actual code that does such, maybe stop bothering people?

**Comment by dirtyboi** [comment]
Ok i see.

What i meant with Hydrus Network and professionally: Hydrus is much longer in the business of booru scraping, so i would consider it pretty reliable. I am fully aware that it is a GUI application, but one could still use the backend code (or just copy portions of it). I know, bigger project - more files and code to go through. But maybe it has a good coding style.

Anyways, just wanted to help you :)

BR,

Dirty Boi
